<?php 
include 'conn.php';
if(!isset($_SESSION['empid'])){
    header("Location: logout.php");
    exit();
}
 $x=$_SESSION['name'];
$empid=$_SESSION['empid'];
$deptid=$_SESSION['deptid'];
if(isset($_POST['report'])){
ob_end_clean();
require_once('tcpdf/tcpdf.php');
$sql = "SELECT l.leavetype,a.*,e.empname,d.deptname from tbl_approval a,tbl_employee e,tbl_leavetype l,tbl_department d where e.emp_id = a.emp_id and l.l_id = a.l_id and e.dept_id = d.dept_id;";
$result = $conn->query($sql);
$current_date = date("Y-m-d");

// Initialize TCPDF
$pdf = new TCPDF();
$pdf->SetCreator('UPLeave');
$pdf->SetAuthor('UPLeave');
$pdf->SetTitle('Leave Details');
$pdf->SetSubject('Database Data');
$pdf->SetKeywords('PDF, Database, TCPDF');

// Add a page
$pdf->AddPage();
// Set font
$pdf->SetFont('times', 'B', 24);
$pdf->SetLineStyle(array('width' => 0.7, 'color' => array(0,0,0)));
$pdf->Rect(3, 3, $pdf->getPageWidth() - 6, $pdf->getPageHeight() - 6);
$pdf->Cell(0, 10, '                                       UPLeave.', 0, 1);
$pdf->SetFont('times', 'B', 20);
$pdf->Cell(0,20, "Leave Summary", 0, 1, 'L');

$pdf->SetFont('times', 'B', 12);
        $pdf->SetX(9); // Set the x-coordinate for starting position of the table

// Output table header with adjusted cell widths
// Output table header with adjusted cell widths
$pdf->Cell(35, 10, 'Employee Name', 1, 0, 'C');
$pdf->Cell(35, 10, 'Department', 1, 0, 'C');
$pdf->Cell(30, 10, 'Leave Type', 1, 0, 'C');
$pdf->Cell(25, 10, 'From Date', 1, 0, 'C');
$pdf->Cell(25, 10, 'To Date', 1, 0, 'C');
$pdf->Cell(37, 10, 'Reason', 1, 1, 'C');

// Iterate through the fetched data and add it to the PDF
if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $lid = $row['l_id'];
        $lql = "SELECT leavetype FROM tbl_leavetype WHERE l_id = $lid";
        $res = $conn->query($lql);
        if ($res) {
            $rows = $res->fetch_assoc();
        }
        $pdf->SetX(9); // Set the x-coordinate for starting position of the table
        $pdf->Cell(35, 10, $row["empname"], 1, 0, 'C');
        $pdf->Cell(35, 10, $row["deptname"], 1, 0, 'C');
        $pdf->Cell(30, 10, $rows['leavetype'], 1, 0, 'C');
        $pdf->Cell(25, 10, $row["st_date"], 1, 0, 'C');
        $pdf->Cell(25, 10, $row["to_date"], 1, 0, 'C');
        $pdf->Cell(37, 10, $row["reason"], 1, 1, 'C');
    }
    $pdf->Cell(0, 10, "Report Generated On : $current_date", 0, 1);
    $pdf->Cell(0, 10, "Report Generated By : $x", 0, 1);

} else {
    $pdf->Cell(0, 10, 'No data found.', 0, 1);
}
$pdf->Output('leavedetails.pdf', 'D');

}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List of Leaves Application</title>

    <link rel="stylesheet" href="assets/css/bootstrap.css">

    <link rel="stylesheet" href="assets/vendors/simple-datatables/style.css">

    <script defer src="assets/fontawesome/js/all.min.js"></script>
    <link rel="stylesheet" href="assets/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="assets/css/app.css">
    <link rel="shortcut icon" href="assets/images/favicon.svg" type="image/x-icon">
</head>

<body>
    <div id="app">
        <div id="sidebar" class='active'>
            <div class="sidebar-wrapper active">
                <div class="sidebar-header" style="height: 50px;margin-top: -30px">
                    <i class="fa fa-users text-success me-4"></i>
                    <span id="span01" style="font-size: smaller;">UPLeave</span>
                </div>
                <div class="sidebar-menu">
                    <ul class="menu">
                        <li class="sidebar-item ">
                            <a href="dean.php" class='sidebar-link'>
                                <i class="fa fa-home text-success"></i>
                                <span>Dashboard</span>
                            </a>
                        </li>
                       
                        <li class="sidebar-item active has-sub">
                            <a href="#" class='sidebar-link'>
                                <i class="fa fa-table text-success"></i>
                                <span>Leave Management</span>
                            </a>
                            <ul class="submenu ">
                                <li>
                                    <a href="dpending_leave.php">Pending Leaves</a>
                                </li>
                                <li>
                                    <a href="dall_leave.php">Leave Summary</a>
                                </li>
                                
                            </ul>
                        </li>
                       
                       
                    </ul>
                </div>
                <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
            </div>
        </div>
        <div id="main">
            <nav class="navbar navbar-header navbar-expand navbar-light">
                <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>
                <button class="btn navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex align-items-center navbar-light ms-auto">
                        <li class="dropdown nav-icon">
                            <a href="#" data-bs-toggle="dropdown"
                                class="nav-link  dropdown-toggle nav-link-lg nav-link-user">
                                
                            </a>
                           
                        </li>
                        <li class="dropdown">
                            <a href="#" data-bs-toggle="dropdown"
                                class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                                <div class="avatar me-1">
                                    <img src="assets/images/admin.png" alt="" srcset="">
                                </div>
                                <div class="d-none d-md-block d-lg-inline-block"><?php echo $x; ?></div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-end">
                                <a class="dropdown-item" href="dvacc.php"><i data-feather="user"></i> Account</a>
                                <a class="dropdown-item" href="dean_update_password.php"><i data-feather="settings"></i> Settings</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="logout.php"><i data-feather="log-out"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="main-content container-fluid">
                <div class="page-title">
                    <div class="row">
                        <div class="col-12 col-md-6 order-md-1 order-last">
                            <h3>Leave Summary</h3>
                        </div>
                        <div class="col-12 col-md-6 order-md-2 order-first">
                            <nav aria-label="breadcrumb" class='breadcrumb-header'>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="dean.php" class="text-success">Dashboard</a>
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">Leave Summary</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
                <section class="section">
                    <div class="card">
                        <div class="card-body">
                            
                            <table class='table' id="table1">
                                <thead>
                                    <tr>
                                        <th>Employee Name</th> 
                                        <th>Department Name</th>
                                        <th>Leave Type</th>
                                        <th>Leave Date</th>
                                        <th>Reason</th>
                                        <th>Remark</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php 
                            $sql = "SELECT l.leavetype,a.*,e.empname,d.deptname from tbl_approval a,tbl_employee e,tbl_leavetype l,tbl_department d where e.emp_id = a.emp_id and l.l_id = a.l_id and e.dept_id = d.dept_id;";
                            $result = $conn->query($sql);
                            while ($row = $result->fetch_assoc()) {

                            ?>
                                    <tr>
                                        <td><?php echo $row['empname']; ?></td>
                                        <td><?php echo $row['deptname']; ?></td>
                                        <td><?php echo $row['leavetype']; ?></td>
                                        <td><?php echo $row['st_date'].' To '.$row['to_date']; ?></td>
                                        <td><?php echo $row['reason']; ?></td>
                                        <td><?php echo $row['remark']; ?></td>

                                        

                                    </tr>
                                   <?php
                            } ?>
                                     
                                </tbody>
                                <center>
                            <form action="#" method="post">
                                <input type="submit" value="Generate Report" name="report" class="btn btn-primary me-1 mb-1">
                            </form></center>
                            </table>
                        </div>
                    </div>

                </section>
            </div>
        </div>
    </div>
    <script src="assets/js/feather-icons/feather.min.js"></script>
    <script src="assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="assets/js/app.js"></script>

    <script src="assets/vendors/simple-datatables/simple-datatables.js"></script>
    <script src="assets/js/vendors.js"></script>

    <script src="assets/js/main.js"></script>
</body>

</html>